update for upload to buildnumber folder

diff --git a/JenkinsFile_PackageAll b/JenkinsFile_PackageAll
--- a/JenkinsFile_PackageAll
+++ b/JenkinsFile_PackageAll
@@ -107,13 +107,15 @@ String getVersionOfARProductFromManifest(manifestFullPath){
 	return version_APRroduct_Pacakge
 }
 
+/**
+* package all products in projectFolder, packageBuildNumber like b1,b2,b3...,b290,..
+*/
 void packageARProduct(projectFolder,packageBuildNumber){
     def productVersionFolder
     sh (
         '''
 			cd ci-script
-			echo java -jar testudo.jar -Dproject='''+projectFolder+''' -Did=* -Dproc=2 -DrunOnJenkins -Drelease
-			java -jar testudo.jar -Dproject='''+projectFolder+''' -Did=* -Dproc=2 -DrunOnJenkins -Drelease=b'''+packageBuildNumber+'''
+			java -jar testudo.jar -Dproject='''+projectFolder+''' -Did=* -Dproc=2 -DrunOnJenkins -Drelease='''+packageBuildNumber+'''
 		'''
         )
 	
@@ -122,6 +124,7 @@ void packageARProduct(projectFolder,packageBuildNumber){
 	def local_linux=getSomeProperties(projectFolder,'local.linux')
 	def arproduct_repo_linux=getSomeProperties(projectFolder,'arproduct.repo.linux')+projectFolder+'/candidate-release/'
 	def manifestFiles = findFiles(glob: '**/'+projectFolder+'/*'+ARProduct_Manifest) 
+	productVersionFolder=productVersionFolder+'/'+packageBuildNumber
 	if(manifestFiles.size()>0){
 		for(int festIndex=0;festIndex<manifestFiles.size();festIndex++){
 		    def productPath=manifestFiles[festIndex].path.replaceAll(ARProduct_Manifest,'')
@@ -129,25 +132,26 @@ void packageARProduct(projectFolder,packageBuildNumber){
 			echo "product name(prefix): ${productName}"
 			def version_APRroduct_Pacakge=getVersionOfARProductFromManifest(manifestFiles[festIndex].path)
 			def files = findFiles(glob: productPath+'/*'+version_APRroduct_Pacakge+'*') 
-	        for(int index=0;index<files.size();index++){
-	            echo "transfer ${files[index].name} to folder $productVersionFolder"
-	            sh( returnStatus: true, script: '''ssh '''+local_linux+'''  'mkdir -p '''+arproduct_repo_linux+productVersionFolder+'''' ''')
-	            def fileExisted=sh(returnStdout: true, script: '''ssh '''+local_linux+''' '[ -e '''+arproduct_repo_linux+productVersionFolder+'/'+files[index].name+''' ]; echo $?' ''').trim()
-	            if(fileExisted=='0'){
-	                echo "Agile Reporter Product Package already exists.No need to download again."
-	            }else{
-	                sh( returnStatus: true, script: 'scp '+files[index].path+' '+local_linux+':'+arproduct_repo_linux+productVersionFolder+'/'+files[index].name)
-	            }
-	        }
+			if(local_linux){
+				sh( returnStatus: true, script: '''ssh '''+local_linux+'''  'mkdir -p '''+arproduct_repo_linux+productVersionFolder+'''' ''')
+				for(int index=0;index<files.size();index++){
+	            	echo "transfer ${files[index].name} to folder $productVersionFolder"
+	            	def fileExisted=sh(returnStdout: true, script: '''ssh '''+local_linux+''' '[ -e '''+arproduct_repo_linux+productVersionFolder+'/'+files[index].name+''' ]; echo $?' ''').trim()
+	            	if(fileExisted=='0'){
+	                	echo "Agile Reporter Product Package already exists.No need to download again."
+	            	}else{
+	                	sh( returnStatus: true, script: 'scp '+files[index].path+' '+local_linux+':'+arproduct_repo_linux+productVersionFolder+'/'+files[index].name)
+	            	}
+	        	}
+			}
 	        //files.each{sh( returnStatus: true, script: 'scp '+it.path+' '+local_linux+':'+arproduct_repo_linux+productVersionFolder+'/'+it.name)}
-            echo "upload product package to S3"
             withAWS(credentials: 'aws') {
-                echo """${files[0].name}, ${files[0].path}, ${files[0].directory}, ${files[0].length}, ${files[0].lastModified}"""
+                //echo """${files[0].name}, ${files[0].path}, ${files[0].directory}, ${files[0].length}, ${files[0].lastModified}"""
                 files.each{s3Upload( bucket:s3_bucket, path:"arproduct/${projectFolder}/CandidateReleases/${productVersionFolder}/${it.name}",includePathPattern:"${it.path}")}
             }
 		}
 	}else{
-	    echo "there is no packages, generated with failures."
+	    error "there is no packages, generated with failures."
 	}
 }
 
